Repository carrot-kpi/monorepo, pull requests merged in 2023-04, with the labels that each got.

#217 Pause the video on Hero unmount
  packages/frontend/src/pages/home/hero/index.tsx
Labels: enhancement

#220 Mobile navbar
  packages/frontend/src/components/connect-wallet/index.tsx
  packages/frontend/src/components/connect-wallet/popovers/account/index.tsx
  packages/frontend/src/components/ui/navbar/index.tsx
  packages/frontend/src/components/ui/navbar/popovers/preferences/index.tsx
  packages/frontend/src/components/ui/navbar/vertical-layout/index.tsx
  packages/frontend/src/pages/campaigns/side-filters/index.tsx
Labels: enhancement

#222 feat: add campaign state and ordering filters to url with search params
  packages/frontend/src/pages/campaigns/index.tsx
  packages/frontend/src/pages/campaigns/select-options/index.ts
Labels: feature

#233 Mobile compatibility
  packages/ui/src/components/input/date-time/index.tsx
  packages/ui/src/components/input/date-time/picker/index.tsx
  packages/ui/src/components/input/date/index.tsx
  packages/ui/src/components/navigation/stepper/index.tsx
Labels: bug
