Repository carrot-kpi/monorepo, pull requests merged in 2023-03, with the labels that each got.

#150 Minor fixes
  packages/sdk/src/fetcher/index.ts
  packages/ui/src/components/input/markdown/index.tsx
Labels: enhancement

#163 Add info popover to radio input
  packages/frontend/src/components/ui/kpi-token-card/index.tsx
  packages/ui/src/components/data-display/timer/index.tsx
  packages/ui/src/components/input/commons/index.tsx
  packages/ui/src/components/input/radio-group/index.tsx
  packages/ui/src/components/input/radio/index.tsx
  packages/ui/src/utils/date/index.ts
Labels: enhancement

#165 Checkbox popover
  packages/ui/src/components/input/checkbox/index.tsx
  packages/ui/src/components/input/radio/index.tsx
Labels: enhancement

#177 Missing classes for checkbox
  packages/ui/src/components/input/checkbox/index.tsx
Labels: bug

#157 Add KPI Token campaign search with Subgraph
  packages/frontend/src/components/ui/navbar/index.tsx
  packages/frontend/src/hooks/useSearch.ts
  packages/frontend/src/pages/campaigns/index.tsx
  packages/frontend/src/pages/campaigns/top-nav/index.tsx
  packages/frontend/src/pages/create/index.tsx
  packages/frontend/src/pages/home/index.tsx
  packages/react/src/hooks/index.ts
  packages/react/src/hooks/useKPITokens.ts
  packages/react/src/hooks/useResetPageScroll.ts
  packages/sdk/src/fetcher/abstraction/index.ts
  packages/sdk/src/fetcher/index.ts
  packages/sdk/src/fetcher/subgraph/index.ts
  packages/sdk/src/fetcher/subgraph/queries/index.ts
Labels: feature

#179 Add onTx to KPITokenPage
  packages/frontend/src/pages/page/index.tsx
  packages/react/src/types/templates.ts
Labels: feature

#186 Broken href link for transactions
  packages/frontend/src/components/connect-wallet/popovers/account/transaction/index.tsx
Labels: bug

#188 Broken tx explorer link
  packages/frontend/src/components/connect-wallet/popovers/account/transaction/index.tsx
  packages/frontend/src/utils/explorers.ts
Labels: bug

#192 Remove horizontal scrolling from fullscreen modal
  packages/frontend/src/components/fullscreen-modal/index.tsx
Labels: bug

#201 Change metamask connector svg viewbox
  packages/frontend/src/assets/connectors/metamask.svg
Labels: bug

#199 Use flexbox instead of grid
  packages/frontend/src/pages/campaigns/index.tsx
Labels: bug

#207 Error boundaries
  packages/frontend/src/i18n/resources/en.ts
  packages/frontend/src/pages/create-with-template-id/index.tsx
  packages/frontend/src/pages/page/index.tsx
  packages/react/src/components/creation-form/kpi-token/index.tsx
  packages/react/src/components/creation-form/oracle/index.tsx
  packages/react/src/components/error-boundary/index.ts
  packages/react/src/components/pages/kpi-token/index.tsx
  packages/react/src/components/pages/oracle/index.tsx
  packages/react/src/components/template-component/index.tsx
  packages/ui/src/assets/error.svg
  packages/ui/src/components/feedback/error-feedback/index.stories.tsx
  packages/ui/src/components/feedback/error-feedback/index.tsx
  packages/ui/src/components/feedback/index.ts
Labels: enhancement
